# Generated by Django 3.2.25 on 2024-09-14 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='prep_time',
            new_name='cooking_time',
        ),
    ]
