# Generated by Django 3.2.25 on 2024-09-17 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20240917_2207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_favorited',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_in_shopping_cart',
        ),
        migrations.AddField(
            model_name='userrecipe',
            name='is_favorited',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userrecipe',
            name='is_in_shopping_cart',
            field=models.BooleanField(default=False),
        ),
    ]
