# Generated by Django 3.2.25 on 2024-09-17 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20240917_2210'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userrecipe',
            old_name='is_favorited',
            new_name='is_favorite',
        ),
    ]
