# Generated by Django 3.2.25 on 2024-09-14 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_rename_description_recipe_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='is_favouried',
            new_name='is_favorited',
        ),
    ]
