# Generated by Django 3.2.25 on 2024-09-16 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_shorturl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_subscribed',
        ),
        migrations.AddField(
            model_name='follower',
            name='is_subscribed',
            field=models.BooleanField(default=False),
        ),
    ]
